version: "3.9"

services:
  frontend:
    build:
      context: ./ecommerce/ecommerce-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - webnet

  backend:
    build:
      context: ./ecommerce
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/db
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,16.171.174.66,backend
      - CORS_ALLOWED_ORIGINS=http://16.171.174.66:3000,http://localhost:3000
    networks:
      - webnet

volumes:
  sqlite_data:

networks:
  webnet:

#for production
# backend:
#   volumes:
#     - sqlite_data:/app
